import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const WorkSans = localFont({
  src: [
    {
      path: "./fonts/static/WorkSans-Regular.ttf",
      weight: "100 900",
      style: "normal",
    },
  ],
  variable: "--font-work-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${WorkSans.variable} antialiased`}>{children}</body>
    </html>
  );
}
